# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number # automatically increment by one
    build_app(workspace: "Aruba.xcworkspace", scheme: "Aruba")
    # upload_to_testflight
    slack(message: "Successfully distributed a new beta build",
      success: true,
             slack_url: "https://hooks.slack.com/services/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")
    swiftlint(
    mode: :lint,                            # SwiftLint mode: :lint (default) or :autocorrect
    executable: "Pods/SwiftLint/swiftlint", # The SwiftLint binary path (optional). Important if you've installed it via CocoaPods
    ignore_exit_status: true,               # Allow fastlane to continue even if SwiftLint returns a non-zero exit status (Default: false)
    quiet: true,                            # Don't print status logs like 'Linting ' & 'Done linting' (Default: false)
    strict: false                            # Fail on warnings? (Default: false)
)
# upload to Beta by Crashlytics
 crashlytics(
   # keys for organization: Horus
   api_token: "6729fa0054cffb049c368bb603d2b99ecb15e5d0",
   build_secret: "3156925bda5317825e08155d234a27efe87d98d0302997f93ce8dab2f7daf6df"
 )

  end
  lane :tests do
    run_tests(scheme: "ArubaTests")
  end
end
